import { Task, Category } from '../types';
import { v4 as uuidv4 } from 'uuid';

const categories: Category[] = [
  { id: 'work', name: 'Work', color: '#3B82F6', isDefault: true },
  { id: 'personal', name: 'Personal', color: '#10B981', isDefault: true },
  { id: 'shopping', name: 'Shopping', color: '#F59E0B', isDefault: true },
  { id: 'health', name: 'Health', color: '#EF4444', isDefault: true },
  { id: 'learning', name: 'Learning', color: '#8B5CF6', isDefault: false },
];

const getDateString = (daysFromNow: number): string => {
  const date = new Date();
  date.setDate(date.getDate() + daysFromNow);
  return date.toISOString().split('T')[0];
};

const getISODate = (daysFromNow: number): string => {
  const date = new Date();
  date.setDate(date.getDate() + daysFromNow);
  return date.toISOString();
};

const tasks: Task[] = [
  // Work tasks
  {
    id: uuidv4(),
    title: 'Complete quarterly report',
    description: 'Prepare and submit the Q4 financial report with all department inputs.',
    status: 'pending',
    priority: 'high',
    categoryId: 'work',
    dueDate: getDateString(2),
    dueTime: '17:00',
    reminder: '1hour',
    subtasks: [
      { id: uuidv4(), title: 'Gather sales data', completed: true },
      { id: uuidv4(), title: 'Create charts and graphs', completed: true },
      { id: uuidv4(), title: 'Write executive summary', completed: false },
      { id: uuidv4(), title: 'Review with manager', completed: false },
    ],
    createdAt: getISODate(-5),
    updatedAt: getISODate(-1),
    completedAt: null,
    reminderTriggered: false,
  },
  {
    id: uuidv4(),
    title: 'Team meeting preparation',
    description: 'Prepare agenda and slides for the weekly team sync.',
    status: 'completed',
    priority: 'medium',
    categoryId: 'work',
    dueDate: getDateString(-1),
    dueTime: '09:00',
    reminder: '15min',
    subtasks: [],
    createdAt: getISODate(-7),
    updatedAt: getISODate(-1),
    completedAt: getISODate(-1),
    reminderTriggered: true,
  },
  {
    id: uuidv4(),
    title: 'Review pull requests',
    description: 'Review and approve pending PRs from the frontend team.',
    status: 'pending',
    priority: 'high',
    categoryId: 'work',
    dueDate: getDateString(0),
    dueTime: '12:00',
    reminder: '1hour',
    subtasks: [
      { id: uuidv4(), title: 'PR #142 - Auth refactor', completed: true },
      { id: uuidv4(), title: 'PR #145 - Dashboard updates', completed: false },
      { id: uuidv4(), title: 'PR #147 - API improvements', completed: false },
    ],
    createdAt: getISODate(-2),
    updatedAt: getISODate(0),
    completedAt: null,
    reminderTriggered: false,
  },
  {
    id: uuidv4(),
    title: 'Update project documentation',
    description: 'Update the README and API docs for the new release.',
    status: 'pending',
    priority: 'low',
    categoryId: 'work',
    dueDate: getDateString(7),
    dueTime: null,
    reminder: '1day',
    subtasks: [],
    createdAt: getISODate(-3),
    updatedAt: getISODate(-3),
    completedAt: null,
    reminderTriggered: false,
  },
  {
    id: uuidv4(),
    title: 'Client presentation',
    description: 'Present the new product features to the client stakeholders.',
    status: 'pending',
    priority: 'high',
    categoryId: 'work',
    dueDate: getDateString(5),
    dueTime: '14:00',
    reminder: '1day',
    subtasks: [
      { id: uuidv4(), title: 'Finalize slides', completed: false },
      { id: uuidv4(), title: 'Practice presentation', completed: false },
      { id: uuidv4(), title: 'Test demo environment', completed: false },
    ],
    createdAt: getISODate(-1),
    updatedAt: getISODate(-1),
    completedAt: null,
    reminderTriggered: false,
  },

  // Personal tasks
  {
    id: uuidv4(),
    title: 'Plan weekend trip',
    description: 'Research destinations and book accommodations for the weekend getaway.',
    status: 'pending',
    priority: 'medium',
    categoryId: 'personal',
    dueDate: getDateString(3),
    dueTime: null,
    reminder: 'none',
    subtasks: [
      { id: uuidv4(), title: 'Choose destination', completed: true },
      { id: uuidv4(), title: 'Book hotel', completed: false },
      { id: uuidv4(), title: 'Plan activities', completed: false },
    ],
    createdAt: getISODate(-4),
    updatedAt: getISODate(-2),
    completedAt: null,
    reminderTriggered: false,
  },
  {
    id: uuidv4(),
    title: 'Call mom',
    description: 'Weekly catch-up call with mom.',
    status: 'completed',
    priority: 'medium',
    categoryId: 'personal',
    dueDate: getDateString(-2),
    dueTime: '19:00',
    reminder: '15min',
    subtasks: [],
    createdAt: getISODate(-5),
    updatedAt: getISODate(-2),
    completedAt: getISODate(-2),
    reminderTriggered: true,
  },
  {
    id: uuidv4(),
    title: 'Renew passport',
    description: 'Submit passport renewal application before it expires.',
    status: 'pending',
    priority: 'high',
    categoryId: 'personal',
    dueDate: getDateString(14),
    dueTime: null,
    reminder: '1day',
    subtasks: [
      { id: uuidv4(), title: 'Take new photos', completed: true },
      { id: uuidv4(), title: 'Fill out application', completed: true },
      { id: uuidv4(), title: 'Schedule appointment', completed: false },
    ],
    createdAt: getISODate(-10),
    updatedAt: getISODate(-3),
    completedAt: null,
    reminderTriggered: false,
  },
  {
    id: uuidv4(),
    title: 'Fix leaky faucet',
    description: 'Replace washers in the kitchen faucet.',
    status: 'pending',
    priority: 'low',
    categoryId: 'personal',
    dueDate: getDateString(10),
    dueTime: null,
    reminder: 'none',
    subtasks: [],
    createdAt: getISODate(-14),
    updatedAt: getISODate(-14),
    completedAt: null,
    reminderTriggered: false,
  },
  {
    id: uuidv4(),
    title: 'Organize garage',
    description: 'Sort through items and donate what we no longer need.',
    status: 'pending',
    priority: 'low',
    categoryId: 'personal',
    dueDate: null,
    dueTime: null,
    reminder: 'none',
    subtasks: [],
    createdAt: getISODate(-20),
    updatedAt: getISODate(-20),
    completedAt: null,
    reminderTriggered: false,
  },

  // Shopping tasks
  {
    id: uuidv4(),
    title: 'Weekly grocery shopping',
    description: 'Buy groceries for the week.',
    status: 'pending',
    priority: 'medium',
    categoryId: 'shopping',
    dueDate: getDateString(1),
    dueTime: '10:00',
    reminder: '1hour',
    subtasks: [
      { id: uuidv4(), title: 'Fruits and vegetables', completed: false },
      { id: uuidv4(), title: 'Dairy products', completed: false },
      { id: uuidv4(), title: 'Bread and cereals', completed: false },
      { id: uuidv4(), title: 'Meat and fish', completed: false },
    ],
    createdAt: getISODate(-1),
    updatedAt: getISODate(-1),
    completedAt: null,
    reminderTriggered: false,
  },
  {
    id: uuidv4(),
    title: 'Buy birthday gift for Sarah',
    description: 'Find a thoughtful birthday gift for Sarah\'s party next week.',
    status: 'pending',
    priority: 'high',
    categoryId: 'shopping',
    dueDate: getDateString(4),
    dueTime: null,
    reminder: '1day',
    subtasks: [],
    createdAt: getISODate(-2),
    updatedAt: getISODate(-2),
    completedAt: null,
    reminderTriggered: false,
  },
  {
    id: uuidv4(),
    title: 'Order new running shoes',
    description: 'Replace old running shoes - look for good deals online.',
    status: 'completed',
    priority: 'medium',
    categoryId: 'shopping',
    dueDate: getDateString(-5),
    dueTime: null,
    reminder: 'none',
    subtasks: [],
    createdAt: getISODate(-10),
    updatedAt: getISODate(-5),
    completedAt: getISODate(-5),
    reminderTriggered: false,
  },
  {
    id: uuidv4(),
    title: 'Buy office supplies',
    description: 'Stock up on notebooks, pens, and sticky notes.',
    status: 'pending',
    priority: 'low',
    categoryId: 'shopping',
    dueDate: getDateString(8),
    dueTime: null,
    reminder: 'none',
    subtasks: [],
    createdAt: getISODate(-3),
    updatedAt: getISODate(-3),
    completedAt: null,
    reminderTriggered: false,
  },
  {
    id: uuidv4(),
    title: 'Return Amazon package',
    description: 'Return the defective headphones to Amazon.',
    status: 'pending',
    priority: 'medium',
    categoryId: 'shopping',
    dueDate: getDateString(2),
    dueTime: null,
    reminder: '1day',
    subtasks: [],
    createdAt: getISODate(-4),
    updatedAt: getISODate(-4),
    completedAt: null,
    reminderTriggered: false,
  },

  // Health tasks
  {
    id: uuidv4(),
    title: 'Annual health checkup',
    description: 'Complete annual physical examination with Dr. Smith.',
    status: 'pending',
    priority: 'high',
    categoryId: 'health',
    dueDate: getDateString(6),
    dueTime: '09:30',
    reminder: '1day',
    subtasks: [
      { id: uuidv4(), title: 'Fast for 12 hours before', completed: false },
      { id: uuidv4(), title: 'Bring insurance card', completed: false },
      { id: uuidv4(), title: 'List current medications', completed: true },
    ],
    createdAt: getISODate(-7),
    updatedAt: getISODate(-2),
    completedAt: null,
    reminderTriggered: false,
  },
  {
    id: uuidv4(),
    title: 'Go for a 5K run',
    description: 'Complete the weekly running goal.',
    status: 'completed',
    priority: 'medium',
    categoryId: 'health',
    dueDate: getDateString(-1),
    dueTime: '06:30',
    reminder: '15min',
    subtasks: [],
    createdAt: getISODate(-3),
    updatedAt: getISODate(-1),
    completedAt: getISODate(-1),
    reminderTriggered: true,
  },
  {
    id: uuidv4(),
    title: 'Meal prep for the week',
    description: 'Prepare healthy meals for the upcoming week.',
    status: 'pending',
    priority: 'medium',
    categoryId: 'health',
    dueDate: getDateString(0),
    dueTime: '16:00',
    reminder: '1hour',
    subtasks: [
      { id: uuidv4(), title: 'Plan menu', completed: true },
      { id: uuidv4(), title: 'Buy ingredients', completed: true },
      { id: uuidv4(), title: 'Cook and portion meals', completed: false },
    ],
    createdAt: getISODate(-2),
    updatedAt: getISODate(0),
    completedAt: null,
    reminderTriggered: false,
  },
  {
    id: uuidv4(),
    title: 'Schedule dentist appointment',
    description: 'Book 6-month dental cleaning.',
    status: 'pending',
    priority: 'low',
    categoryId: 'health',
    dueDate: getDateString(14),
    dueTime: null,
    reminder: 'none',
    subtasks: [],
    createdAt: getISODate(-5),
    updatedAt: getISODate(-5),
    completedAt: null,
    reminderTriggered: false,
  },
  {
    id: uuidv4(),
    title: 'Refill prescriptions',
    description: 'Pick up medication refills from the pharmacy.',
    status: 'pending',
    priority: 'high',
    categoryId: 'health',
    dueDate: getDateString(1),
    dueTime: null,
    reminder: '1day',
    subtasks: [],
    createdAt: getISODate(-1),
    updatedAt: getISODate(-1),
    completedAt: null,
    reminderTriggered: false,
  },

  // Learning tasks
  {
    id: uuidv4(),
    title: 'Complete React course',
    description: 'Finish the advanced React patterns course on Udemy.',
    status: 'pending',
    priority: 'medium',
    categoryId: 'learning',
    dueDate: getDateString(21),
    dueTime: null,
    reminder: 'none',
    subtasks: [
      { id: uuidv4(), title: 'Module 1: Advanced Hooks', completed: true },
      { id: uuidv4(), title: 'Module 2: Performance Optimization', completed: true },
      { id: uuidv4(), title: 'Module 3: Testing Patterns', completed: false },
      { id: uuidv4(), title: 'Module 4: State Management', completed: false },
      { id: uuidv4(), title: 'Final Project', completed: false },
    ],
    createdAt: getISODate(-30),
    updatedAt: getISODate(-3),
    completedAt: null,
    reminderTriggered: false,
  },
  {
    id: uuidv4(),
    title: 'Read "Clean Code" book',
    description: 'Finish reading the Clean Code book by Robert C. Martin.',
    status: 'pending',
    priority: 'low',
    categoryId: 'learning',
    dueDate: null,
    dueTime: null,
    reminder: 'none',
    subtasks: [
      { id: uuidv4(), title: 'Chapters 1-5', completed: true },
      { id: uuidv4(), title: 'Chapters 6-10', completed: true },
      { id: uuidv4(), title: 'Chapters 11-15', completed: false },
      { id: uuidv4(), title: 'Chapters 16-17', completed: false },
    ],
    createdAt: getISODate(-45),
    updatedAt: getISODate(-7),
    completedAt: null,
    reminderTriggered: false,
  },
  {
    id: uuidv4(),
    title: 'Practice Spanish on Duolingo',
    description: 'Complete daily Spanish lesson.',
    status: 'completed',
    priority: 'low',
    categoryId: 'learning',
    dueDate: getDateString(0),
    dueTime: '21:00',
    reminder: '15min',
    subtasks: [],
    createdAt: getISODate(-1),
    updatedAt: getISODate(0),
    completedAt: getISODate(0),
    reminderTriggered: true,
  },
  {
    id: uuidv4(),
    title: 'Watch TypeScript tutorial',
    description: 'Learn advanced TypeScript features from YouTube playlist.',
    status: 'pending',
    priority: 'medium',
    categoryId: 'learning',
    dueDate: getDateString(5),
    dueTime: null,
    reminder: 'none',
    subtasks: [
      { id: uuidv4(), title: 'Generics deep dive', completed: true },
      { id: uuidv4(), title: 'Utility types', completed: false },
      { id: uuidv4(), title: 'Decorators', completed: false },
    ],
    createdAt: getISODate(-10),
    updatedAt: getISODate(-5),
    completedAt: null,
    reminderTriggered: false,
  },
  {
    id: uuidv4(),
    title: 'Build a side project',
    description: 'Create a personal portfolio website using Next.js.',
    status: 'pending',
    priority: 'medium',
    categoryId: 'learning',
    dueDate: getDateString(30),
    dueTime: null,
    reminder: 'none',
    subtasks: [
      { id: uuidv4(), title: 'Design mockups', completed: true },
      { id: uuidv4(), title: 'Set up project', completed: true },
      { id: uuidv4(), title: 'Build homepage', completed: false },
      { id: uuidv4(), title: 'Add projects section', completed: false },
      { id: uuidv4(), title: 'Deploy to Vercel', completed: false },
    ],
    createdAt: getISODate(-14),
    updatedAt: getISODate(-7),
    completedAt: null,
    reminderTriggered: false,
  },
];

export const seedData = () => {
  localStorage.setItem('todo_app_tasks', JSON.stringify(tasks));
  localStorage.setItem('todo_app_categories', JSON.stringify(categories));
  window.location.reload();
};

export { tasks, categories };
